services:
  s3mock:
    image: adobe/s3mock:latest
    environment:
      - COM_ADOBE_TESTING_S3MOCK_STORE_RETAIN_FILES_ON_EXIT=true
      - COM_ADOBE_TESTING_S3MOCK_STORE_ROOT=containers3root
      - COM_ADOBE_TESTING_S3MOCK_STORE_INITIAL_BUCKETS=my-example-bucket
    ports:
      - 9090:9090
      - 9191:9191
    volumes:
      - ./locals3root:/containers3root